name: "Docker Tags Action"
description: "Generate Docker Tags for building docker images."
author: "Shane"
branding:
  icon: "tag"
  color: "blue"

inputs:
  image:
    description: "Image Names to Tag"
    required: false
    default: "ghcr.io/${{ github.repository }}"
  tags:
    description: "Extra Tags to Add"
    required: false
  labels:
    description: "Extra Labels to Add"
    required: false
  seperator:
    description: "Output Seperator"
    required: false
  latest:
    description: "Latest Tag"
    required: false
    default: "default"

outputs:
  tags:
    description: "Generated Docker Tags"
  labels:
    description: "Generated Docker Labels"

runs:
  using: "node20"
  main: "dist/index.js"
