name: "Docker Tags"
description: "Generate Docker Tags and Labels for building Docker images with GitHub Actions."
author: "Shane"
branding:
  icon: "tag"
  color: "blue"

inputs:
  images:
    description: "Image Names to Tag"
    required: false
    default: "ghcr.io/${{ github.repository }}"
  tags:
    description: "Extra Tags to Add"
    required: false
  labels:
    description: "Extra Labels to Add"
    required: false
  seperator:
    description: "Output Seperator"
    required: false
  latest:
    description: "Latest Tag"
    required: false
    default: "default"
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"

outputs:
  tags:
    description: "Generated Docker Tags"
  labels:
    description: "Generated Docker Labels"
  annotations:
    description: "Generated Docker Annotations"

runs:
  using: "node20"
  main: "dist/index.js"
